### ElasticSearch API

# https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-cluster-health.html


@endpoint=http://192.168.124.118:9200

# ----------------------- 基本 CRUD -----------------------
### 
GET {{endpoint}}/

### cluster health
GET {{endpoint}}/_cat

### 檢查詳細狀況
GET {{endpoint}}/_cat/health?v

### 檢查 Index
GET {{endpoint}}/_cat/indices?v

### 建立 Index
PUT {{endpoint}}/customer?pretty

### 查 Index 資料
GET {{endpoint}}/customer/_doc/2

### 刪除 Index
DELETE {{endpoint}}/metr*

### 修改 or 新增
PUT {{endpoint}}/customer/_doc/2?pretty
Content-Type: application/json

{
    "name": "John Doe"
}

### 更新
POST {{endpoint}}/customer/_doc/1/_update?pretty
Content-Type: application/json

{
    "doc": {
        "name": "Tony",
        "age": 31
    }
}

### 支援 script
POST {{endpoint}}/customer/_doc/1/_update?pretty
Content-Type: application/json

{
    "script": "ctx._source.age+=1"
}

### 新增
POST {{endpoint}}/customer/_doc/?pretty
Content-Type: application/json

{
    "name": "Jane Doe"
}



### 刪除特定
DELETE {{endpoint}}/customer/_doc/2?pretty

### 
GET {{endpoint}}/lorem/_doc/0


### 
GET {{endpoint}}/logstash-2019.01.27/