### https://www.zabbix.com/documentation/4.0/manual/api
# 多數 APIs 都包含了 get, create, update, delete 方法

@ApiEndpoint=http://192.168.2.158/zabbix
@ApiEndpoint=http://192.168.1.220:7777


// https://www.zabbix.com/documentation/4.0/manual/api/reference/user/login
### 登入
# @name login
GET {{ApiEndpoint}}/api_jsonrpc.php
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "user.login",
    "params": {
        "user": "Admin",
        "password": "zabbix"
    },
    "id": "{{$guid}}",
    "auth": null
}

@token="{{login.response.body.result}}"


//
### 查詢 被監控站台 清單
GET {{ApiEndpoint}}/api_jsonrpc.php
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "host.get",
    //"params": {},
    "params": {
        "output": [
            "hostid",
            "host"
        ],
        "selectInterfaces": [
            "interfaceid",
            "ip"
        ]
    },
    "id": "{{$guid}}",
    "auth": {{token}}
}


//
### 查出被監控端
GET {{ApiEndpoint}}/api_jsonrpc.php
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "service.get",
    "params": {
        "output": "extend",
        "selectDependencies": "extend"
    },
    "id": "{{$guid}}",
    "auth": {{token}}
}

// https://www.zabbix.com/documentation/4.0/manual/api/reference/problem/get
### 查詢 尚未解決的問題
GET {{ApiEndpoint}}/api_jsonrpc.php
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "problem.get",
    "params": {
        "output": "extend",
        "selectAcknowledges": "extend",
        "selectTags": "extend",
        "selectSuppressionData": "extend",
        //"objectids": "15112",
        "recent": "true",
        "sortfield": ["eventid"],
        "sortorder": "DESC"
    },
    "id": "{{$guid}}",
    "auth": {{token}}
}








// https://www.zabbix.com/documentation/4.0/manual/api/reference/user/logout
### 登出
GET {{ApiEndpoint}}/api_jsonrpc.php HTTP/1.1
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "user.logout",
    "params": [],
    "id": "{{$guid}}",
    "auth": {{token}}
}




# ******************************* Useless *******************************
// https://www.zabbix.com/documentation/4.0/manual/api/reference/apiinfo/version
### 尋找 API methods version (4.0.10) (沒啥鳥用)
GET {{ApiEndpoint}}/api_jsonrpc.php HTTP/1.1
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "apiinfo.version",
    "params": {},
    "id": "{{$guid}}",
    "auth": null
}
