
version: "3"

services:
  drone-server-github:
    image: drone/drone:1
    container_name: drone-server-github
    ports:
      - 8083:80
    #   - 8443:443
    volumes:
      - drone-server-github:/data
    restart: always
    environment:
      # Drone
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_AGENTS_ENABLED=true
      # GitHub Config
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      # Other
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true

#   drone-runner-github:
#     image: drone/drone-runner-docker:1
#     container_name: drone-runner-docker
#     restart: always
#     depends_on:
#       - drone-server-github
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     environment:
#       - DRONE_RPC_HOST=${DRONE_RPC_HOST}
#       - DRONE_RPC_PROTO=${DRONE_RPC_PROTO}
#       - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
#       - DRONE_RUNNER_CAPACITY=3

volumes:
  drone-server-github: {}
