# 2018/05/22
FROM sky46821/centos7-python3.6
COPY . /opt/mt/
WORKDIR /opt/mt

# VOLUME D:/mt /opt/mt/
# RUN yum update -y
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python3 get-pip.py
RUN pip3 install -r requirement.txt

# CMD ["python3", "manage.py", "runserver", "--host", "0.0.0.0"]
# python manage.py runserver --host 0.0.0.0

    # yum -y install python3-pip
#     pip3 install -r requirement.txt
# EXPOSE 80
# CMD ["python", "manage.py", "runserver"]

# docker build -t mt D:\mt\.

# docker run -it mt /bin/bash
# docker run -it --name mt --mount mt /bin/bash