### ElasticSearch API

# https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-cluster-health.html


@endpoint=http://192.168.124.95:9200

### 
GET {{endpoint}}/

### cluster health
GET {{endpoint}}/_cat

### 檢查詳細狀況
GET {{endpoint}}/_cat/health?v

### (自由發揮)
GET {{endpoint}}/_cat/indices?v

### 建立 Index
PUT {{endpoint}}/customer?pretty

### 查 Index 資料
GET {{endpoint}}/customer/_doc/1

### 
PUT {{endpoint}}/customer/_doc/1?pretty
Content-Type: application/json

{
    "name": "Tony Chou"
}