
// https://medium.com/%E9%B3%A5-crl/%E5%88%A9%E7%94%A8-google-place-api-%E5%8F%96%E5%BE%97%E5%9C%B0%E9%BB%9E%E8%A9%95%E8%AB%96-7b62cd467dcd

// API 開啟方式, 進入:
// https://developers.google.com/places/web-service/details
// 三條線 > 


###
@GoogleApiPlace=https://maps.googleapis.com/maps/api/place

###
@place=三創


### 1. 取得特定地點的 place_id
# @name getPlace
GET {{GoogleApiPlace}}/findplacefromtext/json?key={{gcpAPI}}&input={{place}}&inputtype=textquery HTTP/1.1

### (擷取變數)
@place_id={{getPlace.response.body.candidates[0].place_id}}


###
@reviewLanguage=zh-TW
### 2. 依照 place_id 取得評論 (只能取得最多人觀看的 5 筆)
GET {{GoogleApiPlace}}/details/json?key={{gcpAPI}}&placeid={{place_id}}&language={{reviewLanguage}} HTTP/1.1



###
@loc=24.1623725,120.6403629
@radius=3000
@searchType=theater

### 3. 特定座標地點, 半徑 radius 米, 搜尋 searchType(店家類型)   (但都找不到資料噎 ZERO_RESULTS)
GET {{GoogleApiPlace}}/nearbysearch/json?location={{loc}}&radius={{radius}}&type={{searchType}}&keyword=cruis&key={{gcpAPI}}

